build_tools.sh

copy build_tools.sh from pokeemerald

build_tools.sh

---

src/file_system.c

Match DecompressAT function!
The global variant is still unmatched.
Most of the credit for the hard parts of matching this go to MCBoy, AKA Pidgey on Discord.

Match one of two decompression functions!

---

INSTALL.md
Makefile
README.md
asm/friend_list_menu.s
asm/kangaskhan_storage_2.s
asm/kecleon_items.s
include/trade_items_menu.h
ld_script.txt
make_tools.mk
src/felicity_bank_1.c
src/gulpin_shop.c
src/kangaskhan_storage.c
src/kangaskhan_storage_2.c
src/kecleon_items.c
src/kecleon_items_1.c
src/post_office_guide.c
src/trade_items_menu.c

Makefile and Install.md Revamp

---

include/moves.h
src/moves.c
src/pokemon_mid.c

GetHMTMMoves and GetLevelUpMoves are a lot closer now than before.

[src/moves.c] Better match two funcs

---

.github/workflows/build.yml

Was a relic from when I first did this github action. INSTALL instructions use the pret repo and have confirmed locally this should match.

Use pret agbcc and not lucky's fork

---

src/gulpin_shop_1.c

Fixing typo that @Kermalis caught after the last PR merged.

Fixed typo

---

src/sprite.c

See: https://decomp.me/scratch/9y4cC
Not sure if the inlined function is used anywhere else, and not sure what exactly to call it for now.

[decomp] match sub_80054BC

---

src/trap.c

`HandleStickyTrap` was an interesting case where I had to create an unused variable for the asm to match.

Fix nonmatchings in trap.c

---

include/adventure_log.h
include/code_801C244.h
include/code_801D9E4.h
include/code_8023144.h
include/hints_menu1.h
include/kecleon_bros2.h
include/kecleon_bros3.h
include/makuhita_dojo2.h
include/personality_test2.h
include/pokemon_news1.h
include/structs/struct_sub80095e4.h
include/wigglytuff_shop1.h
src/adventure_log.c
src/code_801C244.c
src/code_801D9E4.c
src/code_801F428.c
src/code_8023144.c
src/hints_menu1.c
src/kecleon_bros2.c
src/kecleon_bros3.c
src/makuhita_dojo2.c
src/menu_input.c
src/personality_test2.c
src/pokemon_news1.c
src/wigglytuff_shop1.c
src/wonder_mail_3_mid.c
src/wonder_mail_4.c

`sub_80095E4` _almost_ conquered with a fakematch macro. I honestly have no clue what the original code looked like, but that fakematch was the best I could think of. Unfortunately I know it's not 100% right, because `RedrawPartnerSelectionMenu` doesn't match with that fix(it has a random `mov r4, #0` in a _slightly_ different place).
I also unified different structs scattered all over files, which were in fact the same struct.
The code matches without asm, so I'll take that a win even if the solution was less than elegant 😄

Sub 80095 e4 memes

---

src/code_8057824_1.c

This time I didn't have to do anything lol. Just fixed the const rom vars declarations

Match CelebiJoinDialogue

---

src/dungeon_ai_movement.c

Ugly `goto` was needed to move the desired block of code at the function's end.

Match Wander

---

src/dungeon_ai_attack.c

Match HandleUseOrbAction

---

src/text2.c

one `return str;` instead of `break;` turned out to be necessary

Match HandleTextFormat

---

include/pokemon.h
src/pokemon.c
src/pokemon_mid.c

I had to change some mon functions to take s32 argument and then cast to s16, which has been a non-matching pattern so far.

match sub_808CE74 and sub_808CFD0

---

src/code_806FDF4.c

sub_806F660 was a tricky one. 
To get the nonmatching part right, I had to change the 'matching' part. Seeing Blue's output helped a lot and once I wrote it exactly like in Blue, it matched.

match sub_806F660 and sub_806FD18

---

asm/code_807E5AC.s
include/constants/dungeon.h
include/dungeon_pokemon_attributes.h
src/code_8042B34.c
src/code_8048480.c
src/code_805D8C8_1.c
src/code_8069E0C.c
src/code_806CD90.c
src/code_806E8B0.c
src/code_80718D8.c
src/code_8073CF0.c
src/code_8077274_1.c
src/code_807CD9C.c
src/code_807E1A0.c
src/code_808417C.c
src/dungeon_action.c
src/dungeon_ai_attack.c
src/dungeon_ai_movement.c
src/dungeon_ai_targeting.c
src/dungeon_capabilities.c
src/dungeon_move.c
src/dungeon_pokemon_attributes.c
src/move_actions.c
src/move_effects_target.c
src/status.c
src/status_actions.c
src/status_checks_1.c
src/type_effectiveness.c

IsClientOrTeamBase > IsExperienceLocked
HasAbility > AbilityIsActive
HasTactic > IsTacticSet

Synced some symbol names with Sky

---

src/memory.c

I was wondering why the game would just crash with different settings and I finally found out why...

Fix bug in memory.c

---

src/sprite.c

Plus functionally equivalent AddAxSprite (regswaps https://decomp.me/scratch/33KIb )

Match AddSprite

---

include/structs/struct_sub80095e4.h
src/personality_test2.c

Ugly match, just like the whole macro, but it matches.

Match RedrawPartnerSelectionMenu

---

asm/code_805D8C8.s
asm/code_80718D8.s
asm/dungeon_2.s
data/data_810AE24.s
include/moves.h
src/code_8069E0C.c
src/code_809447C.c
src/dungeon_move.c
src/move_actions.c
src/moves.c
src/trap.c

Based on [TheZZAZZGlitch's video](https://www.youtube.com/watch?v=VjIcJAJVSbw).

Document some death text symbols

---

src/dungeon_move.c

Inspired by Seth's [scratch](https://decomp.me/scratch/B6tHf)

Match sub_8056564

---

include/global.h

It already exists here https://github.com/pret/pmd-red/blob/master/include/gba/defines.h#L15

Remove NAKED define from globalh.

---

asm/code_803D110.s
asm/code_8040094.s
asm/code_8099360.s
include/code_8009804.h
include/structs/rgb.h
src/code_2.c
src/code_800558C.c
src/code_8009804.c
src/code_800E9A8.c
src/code_800E9E4.c
src/code_800F034.c
src/code_803D110.c
src/code_803E724.c
src/code_8073CF0.c
src/code_80869E4.c
src/dungeon_map_access.c
src/dungeon_message.c
src/event_flag.c
src/ground_main.c
src/other_menus2.c
src/sound_names.c
src/text.c
src/thank_you_wonder_mail.c
sym_ewram.txt
sym_iwram.txt

Also some minor touches here and there.

Move some EWRAM/IWRAM variables to their respective C files

---

src/pokemon.c

already externed from file system.h

Remove monsterfilearchieve extern from pokemon.h

---

include/music.h
src/music.c
src/party_list_menu.c
src/trade_items_menu.c
src/wonder_mail_main_menu.c

These need to be merged, otherwise we're overflowing `sBGMusicPlayers`
I also changed some ints to s32, because compiler may complain about it.

Merge sSEMusicPlayers and sBGMusicPlayers

---

src/text_1.c

Credits to @mateon1 for sub_8006E94's scratch.

Match sub_8006E94 and clean-up window related functions

---

src/blow_away.c

https://discord.com/channels/442462691542695948/513153025573912576/1357951658046259200

Apply Kermalis's suggestions to sub_807D068
